# FANUC's trajectory controller and ROS joint-state broadcaster, headless.
/fanuc/controller_manager:
  ros__parameters:
    update_rate: 250
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: fanuc_controllers/ScaledJointTrajectoryController

/fanuc/joint_state_broadcaster:
  ros__parameters:
    joints: [J1, J2, J3, J4, J5, J6]
    interfaces: [position, velocity]
    use_local_topics: false

/fanuc/joint_trajectory_controller:
  ros__parameters:
    joints: [J1, J2, J3, J4, J5, J6]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 1.0
      J1: {trajectory: 0.25, goal: 0.02}
      J2: {trajectory: 0.25, goal: 0.02}
      J3: {trajectory: 0.25, goal: 0.02}
      J4: {trajectory: 0.25, goal: 0.02}
      J5: {trajectory: 0.25, goal: 0.02}
      J6: {trajectory: 0.25, goal: 0.02}
